services:
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    container_name: app-personal-website
    # image: personal-website-app:latest
    ports:
      - "4000:4000"
    networks:
      - net
    restart: unless-stopped

  db:
    container_name: db-personal-website
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3357:3306"
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - api_db_net
    restart: unless-stopped

  api:
    build:
      context: ../my-login-app-api
      dockerfile: Dockerfile
    container_name: api-personal-website
    # image: personal-website-api:latest
    environment:
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    ports:
      - "3000:3000"
    networks:
      - net
      - api_db_net
    restart: unless-stopped

volumes:
  db-data:

networks:
  net:
    driver: bridge
  api_db_net:
    driver: bridge
