version: '3.8'
services:
  app:
    image: app-image-name
    container_name: app
    networks:
      - net

  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81' # Panel de administración
      - '443:443'
    volumes:
      - '/opt/nginx-proxy/data:/data'
      - '/opt/nginx-proxy/letsencrypt:/etc/letsencrypt'
    networks:
      - net

networks:
  net:
    driver: bridge
    external: true
