version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    container_name: app
    image: angular-personal-website-app:latest
    networks:
      - net

  nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    container_name: nginx
    image: angular-personal-website-nginx:latest
    ports:
      - "80:80"   # Para HTTP
      - "443:443" # Para HTTPS
    networks:
      - net

networks:
  net:
    driver: bridge
