version: '3.8'
services:
  app:
    build:
      context: ./
      dockerfile: app.Dockerfile
    container_name: app
    networks:
      - net

  nginx:
    build:
      context: ./
      dockerfile: nginx.Dockerfile
    container_name: nginx
    ports:
      - "80:80"   # Para HTTP
      - "443:443" # Para HTTPS
    networks:
      - net

networks:
  net:
    driver: bridge
