version: '3.8'
services:
  app:
    image: app-image-name
    container_name: app
    networks:
      - net

  nginx:
    image: nginx-image-name
    container_name: nginx
    ports:
      - "80:80"   # Para HTTP
      - "443:443" # Para HTTPS
    networks:
      - net

networks:
  net:
    driver: bridge
